{% set name = "aiocircuitbreaker" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiocircuitbreaker-{{ version }}.tar.gz
  sha256: 21cc3ed3a4c40b8004239fedb2630dbecb8d30dab020d201721c9f745bc8f04f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry >=1.1.12
  run:
    - python >={{ python_min }}

test:
  imports:
    - aiocircuitbreaker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GenyaSol/aiocircuitbreaker
  summary: This is an async Python implementation of the circuitbreaker library https://github.com/fabfuel/circuitbreaker.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - xtrojak
    - hechth
